// <auto-generated />
using System;
using FakeMovieTheatre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FakeMovieTheatre.Migrations
{
    [DbContext(typeof(FakeMovieTheatreContext))]
    [Migration("20190815024109_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FakeMovieTheatre.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genre = "Name a pangolin and receive a plush.",
                            Price = 5m,
                            ReleaseDate = new DateTime(2019, 8, 14, 19, 41, 9, 425, DateTimeKind.Local).AddTicks(2613),
                            Title = "The Never Ending story"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
