// <auto-generated />
using System;
using FakeMovieTheatre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FakeMovieTheatre.Migrations
{
    [DbContext(typeof(FakeMovieTheatreContext))]
    partial class FakeMovieTheatreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FakeMovieTheatre.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<string>("Picture");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genre = "This is the never ending story, one of the best movies ever! Adventure",
                            Picture = "images/neverendingstory.jpg",
                            Price = 5m,
                            ReleaseDate = new DateTime(2019, 9, 1, 17, 21, 4, 75, DateTimeKind.Local).AddTicks(2141),
                            Title = "The Never Ending story"
                        },
                        new
                        {
                            ID = 2,
                            Genre = "Extreemely drawn out and boring until an hour in... suspensful and action!",
                            Picture = "images/th2.jpg",
                            Price = 42m,
                            ReleaseDate = new DateTime(2019, 9, 1, 17, 21, 4, 76, DateTimeKind.Local).AddTicks(6992),
                            Title = "King Kong"
                        },
                        new
                        {
                            ID = 3,
                            Genre = "Comedy suspensful and action!",
                            Picture = "images/th.jpg",
                            Price = 69m,
                            ReleaseDate = new DateTime(2019, 9, 1, 17, 21, 4, 76, DateTimeKind.Local).AddTicks(7007),
                            Title = "This is the End"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
